/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as KernelsRouteImport } from './routes/kernels'
import { Route as LabRouteImport } from './routes/lab'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EnvironmentsIdRouteImport } from './routes/environments.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const KernelsRoute = KernelsRouteImport.update({
  id: '/kernels',
  path: '/kernels',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsIdRoute = EnvironmentsIdRouteImport.update({
  id: '/environments/$id',
  path: '/environments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/kernels': typeof KernelsRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/kernels': typeof KernelsRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/kernels': typeof KernelsRoute
  '/lab': typeof LabRoute
  '/network': typeof NetworkRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extensions'
    | '/kernels'
    | '/lab'
    | '/network'
    | '/security'
    | '/settings'
    | '/environments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extensions'
    | '/kernels'
    | '/lab'
    | '/network'
    | '/security'
    | '/settings'
    | '/environments/$id'
  id:
    | '__root__'
    | '/'
    | '/extensions'
    | '/kernels'
    | '/lab'
    | '/network'
    | '/security'
    | '/settings'
    | '/environments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsRoute: typeof ExtensionsRoute
  KernelsRoute: typeof KernelsRoute
  LabRoute: typeof LabRoute
  NetworkRoute: typeof NetworkRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  EnvironmentsIdRoute: typeof EnvironmentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kernels': {
      id: '/kernels'
      path: '/kernels'
      fullPath: '/kernels'
      preLoaderRoute: typeof KernelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments/$id': {
      id: '/environments/$id'
      path: '/environments/$id'
      fullPath: '/environments/$id'
      preLoaderRoute: typeof EnvironmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsRoute: ExtensionsRoute,
  KernelsRoute: KernelsRoute,
  LabRoute: LabRoute,
  NetworkRoute: NetworkRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  EnvironmentsIdRoute: EnvironmentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
